OLED_ENABLE = no
ENCODER_ENABLE = no
RGBLIGHT_ENABLE = yes      # Enable keyboard RGB underglow
MOUSEKEY_ENABLE = no  
COMBO_ENABLE = yes
LEADER_ENABLE = no
KEY_OVERRIDE_ENABLE = yes
TAP_DANCE_ENABLE = yes
# Saves a bunch of memory
EXTRAFLAGS += -flto
CONSOLE_ENABLE = no
VERBOSE = no
DEBUG_MATRIX_SCAN_RATE  = no
DEBUG_MATRIX = no
MAGIC_ENABLE = no
SPACE_CADET_ENABLE = no
GRAVE_ESC_ENABLE = no
